#!/bin/sh

# Mount minimal filesystems
mount -t proc none /proc
mount -t sysfs none /sys

# Welcome message
echo "-----------------------------------"
echo "Welcome to KLKD (Kalpit's Linux Kernel Dev) Lab!"
echo "Kernel: $(uname -r)"
echo "-----------------------------------"

# Drop to a shell
while true; do
    setsid cttyhack /bin/sh
    echo "Shell exited! Restarting..."
done

# Fallback if loop fails
echo "Init failed! Powering off..."
poweroff -f
